

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/"
command = "npm run build"





[build.processing.js]

[build.services]
