[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
<<<<<<< HEAD
publish = ".next"
publishOrigin = 'config"
commandOrigin = "config"

=======
publish = "dist"
>>>>>>> d69642b0ab936214a26f9c5e0135071caf78e085
base = "/"
command = "npm run build"





[build.processing.js]

[build.services]
